
server:
  port: 8080

spring:
#  jpa:
#    show-sql: true
  datasource:
    name: cq
    url: jdbc:mysql://localhost:3306/cq?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    #打印sql
logging:
  level:
    com.cq.hll.mapper: debug
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.cq.hll.entity  # 注意：对应实体类的路径
